# Generated by Django 3.2.7 on 2021-09-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='execerpt',
            new_name='excerpt',
        ),
    ]
